[project]
name = "literate-enigma"
version = "0.1.0"
description = "A simple airgapped document parsing tool using locally procured LLM insights to allow users to ask questions about uploaded documents. Features OCR and Vision based document process as well as a RAG document recovery storage tool."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
